//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public System.Guid id { get; set; }
        public System.Guid party_id { get; set; }
        public System.Guid song_id { get; set; }
        public System.Guid user_id { get; set; }
        public int position { get; set; }
        public string status { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Song Song { get; set; }
        public virtual UserBox UserBox { get; set; }
    }
}
